Fix generate_kubeconfig to work against specified namespace
Summary:
A minor fix is required to make this script work against a given namespace. Currently, it looks for given service account token in the default namespace instead of the given namespace. It can end up finding the wrong secret name this way.
```
[sneelakantan@dev-server-sneelakantan ~]$ python3 generate_kubeconfig.py -s yugabyte-platform-universe-management -n ${YBA_NAMESPACE}
Running command: kubectl --namespace subbu-univ config current-context
Running command: kubectl --namespace subbu-univ config get-contexts gke_yugabyte_us-west1_k8s-portal-yb --no-headers
Running command: kubectl --namespace subbu-univ config view -o jsonpath="{.clusters[?(@.name =="gke_yugabyte_us-west1_k8s-portal-yb")].cluster.server}"
Running command: kubectl --namespace subbu-univ get sa yugabyte-platform-universe-management -o json
Running command: kubectl get secret --field-selector type=kubernetes.io/service-account-token -o jsonpath="{.items[?(@.metadata.annotations.kubernetes\.io/service-account\.name == "yugabyte-platform-universe-management")].metadata.name}"
Running command: kubectl --namespace subbu-univ get secret yugabyte-platform-universe-management-token-jtxtz -o json
Error from server (NotFound): secrets "yugabyte-platform-universe-management-token-jtxtz" not found
Traceback (most recent call last):
  File "generate_kubeconfig.py", line 155, in <module>
    secret_data = get_secret_data(secret, args["namespace"])
  File "generate_kubeconfig.py", line 73, in get_secret_data
    secret_json = run_command(["get", "secret", secret], namespace)
  File "generate_kubeconfig.py", line 27, in run_command
    output = check_output(command)
  File "/usr/share/python-3.8.16/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/share/python-3.8.16/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['kubectl', '--namespace', 'subbu-univ', 'get', 'secret', 'yugabyte-platform-universe-management-token-jtxtz', '-o', 'json']' returned non-zero exit status 1.
```

Test Plan: Generated the kubeconfig successfully after this fix.

Reviewers: bgandhi, sanketh

Reviewed By: bgandhi

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D28327