[PLAT-12307] Fix handling of AZ:0 in AKS
Summary:
We recently had a case when user was trying to deploy a multi AZ cluster in AKS.
AKS uses Zone name "0" for system zone.
When creating a provider using suggested provider config, we pick up zone 0, which is as expected.
However when creating universe with that provider it fails with a message saying

```
StatefulSet in version "v1" cannot be handled as a StatefulSet: json: cannot unmarshal number into Go struct field NodeSelectorRequirement.spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms.matchExpressions.values of type string
```

We need to explicitly quote AZ when defining affinity rules, otherwise it is interpreted as a string.

Test Plan:
Tested by deploying the fixed chart, helm install goes through.

Before change.

```

[centos@dev-server-anijhawan-4 yugabyte]$ helm install . -f test.val.yaml --generate-name -n test

Error: INSTALLATION FAILED: 2 errors occurred:

StatefulSet in version "v1" cannot be handled as a StatefulSet: json: cannot unmarshal number into Go struct field NodeSelectorRequirement.spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms.matchExpressions.values of type string

StatefulSet in version "v1" cannot be handled as a StatefulSet: json: cannot unmarshal number into Go struct field NodeSelectorRequirement.spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms.matchExpressions.values of type string
```

After change

```
[centos@dev-server-anijhawan-4 yugabyte]$ helm install . -f test.val.yaml --generate-name -n test1
W0118 00:32:49.235947 2330848 warnings.go:70] spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: failure-domain.beta.kubernetes.io/zone is deprecated since v1.17; use "topology.kube
rnetes.io/zone" instead
W0118 00:32:49.237255 2330848 warnings.go:70] spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: failure-domain.beta.kubernetes.io/zone is deprecated since v1.17; use "topology.kube
rnetes.io/zone" instead
NAME: chart-1705537967
LAST DEPLOYED: Thu Jan 18 00:32:47 2024
NAMESPACE: test1
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
```

Reviewers: getourneau, sanketh, bgandhi, ysharma-contractor, dshubin, vkumar

Reviewed By: dshubin

Subscribers: yugaware

Differential Revision: https://phorge.dev.yugabyte.com/D31768