Provide template value to override Nginx `ssl_protocols` setting
Summary:
Also, validate input to ensure user doesn't accidentally specify an
invalid setting (currrently only support TLSv1.0-3).

Test Plan:
Run `helm install` with valid and invalid test cases:

```
$ helm install test ./stable/yugaware --set tls.enabled="true" --set tls.sslProtocols="TLSv1.2 TLSv1.3" --dry-run
...
      ssl_protocols TLSv1.2 TLSv1.3;
...

$ helm install test ./stable/yugaware --set tls.enabled="true" --set tls.sslProtocols="bad" --dry-run
Error: template: yugaware/templates/configs.yaml:143:23: executing "yugaware/templates/configs.yaml" at <include "validate_nginx_ssl_protocols" .>: error calling include: template: yugaware/templates/_helpers.tpl:78:8: executing "validate_nginx_ssl_protocols" at <fail (cat "Please specify valid tls.sslProtocols, must match regex:" $sslProtocolsRegex)>: error calling fail: Please specify valid tls.sslProtocols, must match regex: ^((TLSv1.[0-3])(?: ){0,1}){1,4}$
```

Also, ran a curl against the deployed platform to confirm that the SSL versions setting was being set.

With only TLSv1.3 enabled, TLSv1.2 requests fail:
```
jason@jv-work:~/code/charts-tls-fix$ curl -I -v --tlsv1.3 --tls-max 1.3 https://10.152.183.145:443
*   Trying 10.152.183.145:443...
* TCP_NODELAY set
* Connected to 10.152.183.145 (10.152.183.145) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=*.cloud.yugabyte.com
*  start date: Aug  1 00:00:00 2019 GMT
*  expire date: Jul 31 12:00:00 2021 GMT
...

jason@jv-work:~/code/charts-tls-fix$ curl -I -v --tlsv1.2 --tls-max 1.2 https://10.152.183.145:443
*   Trying 10.152.183.145:443...
* TCP_NODELAY set
* Connected to 10.152.183.145 (10.152.183.145) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS alert, protocol version (582):
* error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
* Closing connection 0
curl: (35) error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
```

Reviewers: arnav, sanketh, daniel

Reviewed By: daniel

Subscribers: yugaware

Differential Revision: https://phabricator.dev.yugabyte.com/D10562